# ç›¸å…³é…ç½®è¯´æ˜
  # favicon: ç½‘ç«™å›¾æ ‡
  # avatar: ä¸»é¢˜ç”¨æˆ·å¤´åƒä¸æ˜µç§°
  # rss: rssè®¢é˜…
  # prevnext: æ–‡ç« æœ«å°¾çš„ä¸Šä¸€é¡µä¸ä¸‹ä¸€é¡µ
  # footer: é¡µè„šä¿¡æ¯
  # search: æ–‡ç« æœç´¢

# enable: æ˜¯å¦å¼€å¯ç›¸åº”åŠŸèƒ½ï¼Œå¯é€‰true || false

# ç½‘ç«™å›¾æ ‡
favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

# ç”¨æˆ·å¤´åƒä¸æ˜µç§°
avatar:
  enable: true
  photo: /images/avatar.png
  path: /

# æ–‡ç« æœ«å°¾çš„ä¸Šä¸€é¡µä¸ä¸‹ä¸€é¡µ
prevnext:
  enable: true

# é“¾æ¥ä¿¡æ¯
link: 
  -
    name: Blog
    title: Blog
    icon: emoji-friendly
    path: /archives
  -
    name: Docs
    title: Docs
    icon: tags
    path: /
    target: _blank
  -
    name: GitHub
    title: GitHub
    icon: github
    path: https://github.com/heycn
    target: _blank
  -
    name: WeChat
    title: WeChat
    icon: wechat
    path: /images/wechat.jpg
    target: _blank
  -
    name: Twitter
    title: Twitter
    icon: twitter
    path: https://twitter.com/heycn_112
    target: _blank
  -
    name: Email
    title: Email
    icon: envelope
    path: mailto:heycn@foxmail.com

# é¡¹ç›®ä¿¡æ¯
project: 
  -
    name: flag ui
    describe: vue3 UIç»„ä»¶åº“
    path: https://heycn.github.io/flag-ui-website/
  -
    name: æ¢…å¼€äºŒåº¦
    describe: æ¢…èŠ±ç”Ÿé•¿åŠ¨ç”»å° demo
    path: https://heycn.github.io/plum-website/
  -
    name: feeling ui
    describe: vue2 UIç»„ä»¶åº“
    path: https://heycn.gitee.io/feeling-ui/
  -
    name: mini redux
    describe: ä¸€ä¸ªç®€å•çš„ redux å®ç°
    path: https://github.com/heycn/mini-redux/
  -
    name: tree animation
    describe: ä¼šåŠ¨çš„æ ‘
    path: https://heycn.github.io/tree-animation-website/
  -
    name: å£è¢‹è®°è´¦
    describe: ç”¨æ¥è®°è´¦çš„ webapp
    path: https://heycn.github.io/pocket-react-website/
  -
    name: ä¼šåŠ¨çš„çš®å¡ä¸˜
    describe: ç”»ä¸ªçš®å¡ä¸˜ç»™ä½ ï¼
    path: https://heycn.github.io/pikachu/dist/index.html/

greetings:
  -
    label: ğŸ‘‹ Hi,
  -
    label: I'm ChenNan.

introduction:
  -
    label: A software developer. Most of my work is Front-End.
  -
    label: I like making interesting projects.
  -
    label: Outside of programming, I enjoy running, reading and drink beer.
  - 
    label: Find me on 
           <a href="https://github.com/heycn" target="_blank">GitHub</a>, 
           <a href="https://twitter.com/heycn_112" target="_blank">Twitter</a>, 
           <a href="https://juejin.cn/user/4372092371864984" target="_blank">æ˜é‡‘</a> 
           or 
           <a href="https://www.zhihu.com/people/wo-bu-shi-chen-nan" target="_blank">çŸ¥ä¹.</a> 
           Mail me at
           <a href="mailto:heycn@foxmail.com">heycn@foxmail.com</a>.

footer:
  -
    name:
    path:
  -
    name:
    path:

# æ–‡ç« æœç´¢
# TODO: æœç´¢åŠŸèƒ½æš‚æœªå®ç°
search:
  enable: false
  placeholder:
